name: Setup Action

description: Setup Project

inputs:
  PLAY_CONFIG_JSON:
    description: 'Play store config in base64 format'
    required: true
  UPLOAD_KEYSTORE_KJS:
    description: 'Upload keystore in base64 format'
    required: true
  KEY_PROPERTIES:
    description: 'Key properties in base64 format'
    required: true

runs:
  using: composite
  steps:
    - uses: kuhnroyal/flutter-fvm-config-action@v1

    - name: Cache Primes
      id: cache-build
      uses: actions/cache@v3
      with:
        path: |
          build
        key: ${{ runner.os }}-build

    - uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ env.FLUTTER_VERSION }}
        channel: ${{ env.FLUTTER_CHANNEL }}
        cache: true

    - name: Flutter version
      shell: bash
      run: flutter --version

    - name: Install packages
      shell: bash
      run: flutter pub get

    - name: Set Play Store Configurations
      uses: ./.github/actions/play-store-config
      with:
        PLAY_CONFIG_JSON: ${{ inputs.PLAY_CONFIG_JSON }}
        UPLOAD_KEYSTORE_KJS: ${{ inputs.UPLOAD_KEYSTORE_KJS }}
        KEY_PROPERTIES: ${{ inputs.KEY_PROPERTIES }}
