name: Set Play Store Configurations

description: Configure play store deployment

inputs:
  PLAY_CONFIG_JSON:
    description: 'Play store config in base64 format'
    required: true
  UPLOAD_KEYSTORE_KJS:
    description: 'Upload keystore in base64 format'
    required: true
  KEY_PROPERTIES:
    description: 'Key properties in base64 format'
    required: true

runs:
  using: composite
  steps:
    - uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically

    - name: Configure Keystore
      shell: bash
      run: |
        mkdir -p secrets/
        echo "$ANDROID_KEYSTORE_FILE" > secrets/upload-keystore.jks.b64
        base64 -d -i secrets/upload-keystore.jks.b64 > android/upload-keystore.jks
        echo "KEY_PROPERTIES" > secrets/key.properties.b64
        base64 -d -i secrets/key.properties.b64 > android/key.properties
      env:
        UPLOAD_KEYSTORE_KJS: ${{ inputs.UPLOAD_KEYSTORE_KJS }}
        KEY_PROPERTIES: ${{ inputs.KEY_PROPERTIES }}

    - name: Create Google Play Config file
      shell: bash
      run : |
        mkdir -p secrets/
        echo "$PLAY_CONFIG_JSON" > secrets/play_config.json.b64
        base64 -d -i secrets/play_config.json.b64 > android/play_config.json
      env:
        PLAY_CONFIG_JSON: ${{ inputs.PLAY_CONFIG_JSON }}
