name: Set Play Store Configurations

description: Configure play store deployment

inputs:
  PLAY_CONFIG_JSON:
    description: 'Play store config in base64 format'
    required: true
  UPLOAD_KEYSTORE_KJS:
    description: 'Upload keystore in base64 format'
    required: true
  KEY_PROPERTIES:
    description: 'Key properties in base64 format'
    required: true

runs:
  using: composite
  steps:
    - uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically

    - name: Configure Keystore
      shell: bash
      run: |
        echo $UPLOAD_KEYSTORE_KJS | base64 -d -i > android/upload-keystore.jks
        echo $KEY_PROPERTIES | base64 -d -i > android/key.properties
      env:
        UPLOAD_KEYSTORE_KJS: ${{ inputs.UPLOAD_KEYSTORE_KJS }}
        KEY_PROPERTIES: ${{ inputs.KEY_PROPERTIES }}

    - name: Create Google Play Config file
      shell: bash
      run : |
        echo $PLAY_CONFIG_JSON | base64 -d -i > android/play_config.json
      env:
        PLAY_CONFIG_JSON: ${{ inputs.PLAY_CONFIG_JSON }}
