# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Google Play internal testing"
  lane :internal do
    gradle(task: "clean")
    gradle(task: "assembleRelease")
    upload_to_play_store(track: 'internal', skip_upload_changelogs: true)

    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "informational lane that displays the currently promoted version codes or release name"
  lane :info_internal do
    google_play_track_version_codes(track: 'internal')
    google_play_track_release_names(track: 'internal')
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean")
    gradle(task: "assembleRelease")
    upload_to_play_store
  end

  desc "informational lane that displays the currently promoted version codes or release name"
  lane :info do
    google_play_track_version_codes
    google_play_track_release_names
  end
end
