name: Production Release

on: workflow_dispatch

jobs:
  android-production-release:
    name: Android Production Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup project
        uses: ./.github/actions/setup
        with:
          PLAY_CONFIG_JSON: ${{ secrets.PLAY_CONFIG_JSON }}
          UPLOAD_KEYSTORE_KJS: ${{ secrets.UPLOAD_KEYSTORE_KJS }}
          KEY_PROPERTIES: ${{ secrets.KEY_PROPERTIES }}

      - name: Release app to Production track 🚀
        run: |
          cd android/
          bundle exec fastlane production
          bundle exec fastlane info

