name: Tagged Release

on:
  push:
    tags:
      - "v*"

jobs:
  test:
    name: Testing
    uses: ./.github/workflows/test.yml

  github-release:
    name: Github Release
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup project
        uses: ./.github/actions/setup
        with:
          PLAY_CONFIG_JSON: ${{ secrets.PLAY_CONFIG_JSON }}
          UPLOAD_KEYSTORE_KJS: ${{ secrets.UPLOAD_KEYSTORE_KJS }}
          KEY_PROPERTIES: ${{ secrets.KEY_PROPERTIES }}

      - name: Build APK
        shell: bash
        run: flutter build apk

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            LICENSE.md
            build/app/outputs/apk/release/app-release.apk

  android-alpha-release:
    name: Android Alpha Release
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup project
        uses: ./.github/actions/setup
        with:
          PLAY_CONFIG_JSON: ${{ secrets.PLAY_CONFIG_JSON }}
          UPLOAD_KEYSTORE_KJS: ${{ secrets.UPLOAD_KEYSTORE_KJS }}
          KEY_PROPERTIES: ${{ secrets.KEY_PROPERTIES }}

      - name: Release app to Alpha track 🚀
        run: |
          cd android/
          bundle exec fastlane alpha
          bundle exec fastlane alpha_info
