name: Testing

on:
  workflow_call:
  pull_request:

jobs:
  test:
    # This job will run on ubuntu virtual machine
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup project
        uses: ./.github/actions/setup
        with:
          PLAY_CONFIG_JSON: ${{ secrets.PLAY_CONFIG_JSON }}
          UPLOAD_KEYSTORE_KJS: ${{ secrets.UPLOAD_KEYSTORE_KJS }}
          KEY_PROPERTIES: ${{ secrets.KEY_PROPERTIES }}

      # Statically analyze the Dart code for any errors.
      - name: Run static analysis
        shell: bash
        run: flutter analyze .
